"""
Tiny example your file-store bots can use for central force-sub checks.

Only the manager bot needs to be admin in the force-sub channel. Your file bot
calls the manager service before serving protected files. Use the personal API
key generated by /apikey rotate in the manager bot.
"""

import os
import requests

MANAGER_URL = os.environ["MANAGER_URL"].rstrip("/")
API_SECRET = os.environ["MANAGER_API_SECRET"]


def is_subscribed(user_id: int, channel: str) -> bool:
    response = requests.post(
        f"{MANAGER_URL}/api/check-subscription",
        headers={"X-API-Key": API_SECRET},
        json={"user_id": user_id, "channel": channel},
        timeout=15,
    )
    response.raise_for_status()
    return bool(response.json()["subscribed"])


if __name__ == "__main__":
    print(is_subscribed(123456789, "@your_channel"))
